package recording.audio.prototype;

import java.awt.Color;
import javax.swing.JFrame;

/**
 * A GUI frame for the recording program.
 * @author Jafeth
 * TODO: Create language interface to support multiple languages.
 */
public class RecorderGUI extends javax.swing.JFrame {

    private final SoundRecorder recorder;//An instance of the recorder class to do the actual recording.
    
    /**
     * Creates new form RecorderGUI
     */
    public RecorderGUI() {
        recorder = new SoundRecorder(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

		//Code to define the UI elements.
        jPanel1 = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();

		//Default close operation is set to exit program.
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		//Initialises the jPanel1 UI element.
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

		//Sets the text for the title label.
        titleLabel.setText("Recording prototype");

		//Sets the text for the start button.
        startButton.setText("START");
		
		//Sets an actionlistener to the startbutton so the system can respond when it is pressed.
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

		//Sets the text for the stop button.
        stopButton.setText("STOP");
		
		//Sets an actionlistener to the startbutton so the system can respond when it is pressed.
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

		//Sets the layout parameters. Created by the IDE.
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopButton)
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(stopButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Is called when the start button is pressed. Starts the recording.
     * @param evt The event of the button being pressed.
     */
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        this.recorder.startRecording();
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * Is called when the stop button is pressed. Stops the recording.
     * @param evt The event of the button being pressed.
     */
    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        this.recorder.finish();
    }//GEN-LAST:event_stopButtonActionPerformed
    
    public void formatNotSupportedActionPerformed()
    {
        //Tells the user the microphone can not record the currently set audioformat.
        //Colour is red to imply an error.
        this.messageLabel.setForeground(Color.RED);
        this.messageLabel.setText("Audio format not supported on the microphone.");
    }
    
    /**
     * Is triggered when the attempt to find a microphone is unsuccessful.
     */
    public void lineNotFoundActionPerformed()
    {
        //Tells the user a microphone could not be found.
        //Colour is red to imply an error.
        this.messageLabel.setForeground(Color.RED);
        this.messageLabel.setText("Microphone not found.");
    }
    
    /**
     * Is triggered when a recording start attempt is successful.
     */
    public void recordingStartedActionPerformed()
    {
        //Tells the user the recording start attempt was successful.
        //Colour is black to imply being just a notification.
        this.messageLabel.setForeground(Color.BLACK);
        this.messageLabel.setText("Recording started");
    }
    
    /**
     * Is triggered when a recording start attempt is unsuccessful.
     */
    public void recordingNotStartedActionPerformed()
    {
        //Tells the user the recording start attempt was unsuccessful.
        //Colour is red to imply an error.
        this.messageLabel.setForeground(Color.RED);
        this.messageLabel.setText("Recording not started");
    }
    
    /**
     * Is triggered when a recording stop attempt is successful.
     */
    public void recordingStoppedActionPerformed()
    {
        //Tells the user the recording stop attempt was successful.
        //Colour is black to imply being just a notification.
        this.messageLabel.setForeground(Color.BLACK);
        this.messageLabel.setText("Recording stopped");
    }
    
    /**
     * Is triggered when a recording stop attempt is unsuccessful.
     */
    public void recordingNotStoppedActionPerformed()
    {
        //Tells the user the recording stop attempt was unsuccessful.
        //Colour is red to imply an error.
        this.messageLabel.setForeground(Color.RED);
        this.messageLabel.setText("Recording not stopped");
    }
    
    /**
     * The start of the program. Creates the GUI.
     * @param args The command line arguments.
     */
    public static void main(String[] args)
    {
        //Creates a new recorder GUI.
        RecorderGUI gui = new RecorderGUI();
        
        //Sets the default operation of the close button of the GUI to exit.
        gui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        //Makes the GUI visible.
        gui.setVisible(true);
    }
    
    //Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;//Generic panel to hold other UI elements.
    private javax.swing.JLabel messageLabel;//Message label to tell the user what the program is doing and inform them about errors.
    private javax.swing.JButton startButton;//A button to start recording.
    private javax.swing.JButton stopButton;//A button to stop recording.
    private javax.swing.JLabel titleLabel;//Label with the title of the program.
    //End of variables declaration//GEN-END:variables
}